# Generated by Django 5.2.1 on 2025-06-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_billingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingAddress',
        ),
    ]
