# Generated by Django 5.2.1 on 2025-06-05 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_list',
            old_name='slug',
            new_name='slag',
        ),
    ]
