# Generated by Django 5.2.1 on 2025-06-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_list',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='category'),
        ),
    ]
