# Generated by Django 5.2.1 on 2025-06-05 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_list_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category_list',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
