# Generated by Django 5.2.1 on 2025-06-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_products_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='offer_price',
            field=models.IntegerField(default=10),
        ),
    ]
