# Generated by Django 5.2.1 on 2025-06-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_products_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='actual_price',
            field=models.IntegerField(default=0),
        ),
    ]
