# Generated by Django 5.2.1 on 2025-06-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_products_actual_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.CharField(default=1, max_length=150),
        ),
    ]
