# Generated by Django 5.2.1 on 2025-06-09 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_products_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_list',
            old_name='slag',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='slag',
            new_name='slug',
        ),
    ]
