# Generated by Django 5.2.1 on 2025-06-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_slag_category_list_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Category',
            new_name='category',
        ),
    ]
