# Generated by Django 5.2.1 on 2025-06-11 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('image', models.ImageField(upload_to='products')),
                ('description', models.TextField()),
                ('stock', models.IntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('offer', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('quantity', models.CharField(default=1, max_length=150)),
                ('offer_price', models.IntegerField(default=10)),
                ('actual_price', models.IntegerField(default=0)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category_list')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
