# Generated by Django 5.2.1 on 2025-06-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_products_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Productss',
        ),
    ]
